let a=12;
let b=123.56;
let str='Hello';
let isLocked=true;
let age=null;
let x;
let n=25687956324578952364423n;
console.log(`a= ${a} and typeof ${typeof a}`);
console.log(`b= ${b} and typeof ${typeof b}`);
console.log(`str= ${str} and typeof ${typeof str}`);
console.log(`isLocked= ${isLocked} and typeof ${typeof isLocked}`);
console.log(`age= ${age} and typeof ${typeof age}`);
console.log(`x= ${x} and typeof ${typeof x}`);
console.log(`n= ${n} and typeof ${typeof n}`);
console.log("6"/"2");
console.log("6"/"0");
console.log("abc"/"0");
console.log('type of a',typeof Math);
console.log('type of null',typeof null);